// <auto-generated />
using System;
using ClientSearch.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClientSearch.Web.Migrations
{
    [DbContext(typeof(ClientInMemoryContext))]
    [Migration("20250718102415_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("ClientSearch.Data.Entities.Client", b =>
                {
                    b.Property<Guid>("ClientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientDetails")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientEmployeeSizeRange")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientSource")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ServicingOffice")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("ClientID");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            ClientID = new Guid("c2010001-0000-0000-0000-000000000001"),
                            ClientDetails = "IT consulting firm",
                            ClientEmployeeSizeRange = "100-500",
                            ClientName = "TechNova Solutions",
                            ClientSource = "A1",
                            Country = "India",
                            ServicingOffice = "Bangalore",
                            State = "KA"
                        },
                        new
                        {
                            ClientID = new Guid("c2010001-0000-0000-0000-000000000002"),
                            ClientDetails = "Eco product supplier",
                            ClientEmployeeSizeRange = "50-200",
                            ClientName = "GreenLeaf Corp",
                            ClientSource = "A2",
                            Country = "India",
                            ServicingOffice = "Mumbai",
                            State = "MH"
                        },
                        new
                        {
                            ClientID = new Guid("c2010001-0000-0000-0000-000000000003"),
                            ClientDetails = "Marine tech company",
                            ClientEmployeeSizeRange = "200-1000",
                            ClientName = "BlueWave Global",
                            ClientSource = "A1",
                            Country = "USA",
                            ServicingOffice = "Dallas",
                            State = "TX"
                        },
                        new
                        {
                            ClientID = new Guid("c2010001-0000-0000-0000-000000000004"),
                            ClientDetails = "Software development",
                            ClientEmployeeSizeRange = "500-1500",
                            ClientName = "InnoSoft Pvt Ltd",
                            ClientSource = "A2",
                            Country = "India",
                            ServicingOffice = "Chennai",
                            State = "TN"
                        },
                        new
                        {
                            ClientID = new Guid("c2010001-0000-0000-0000-000000000005"),
                            ClientDetails = "Data analytics firm",
                            ClientEmployeeSizeRange = "150-600",
                            ClientName = "SilverLine Analytics",
                            ClientSource = "A1",
                            Country = "USA",
                            ServicingOffice = "New York",
                            State = "NY"
                        },
                        new
                        {
                            ClientID = new Guid("c2010001-0000-0000-0000-000000000006"),
                            ClientDetails = "Cloud services provider",
                            ClientEmployeeSizeRange = "300-800",
                            ClientName = "Orbit Tech",
                            ClientSource = "A2",
                            Country = "India",
                            ServicingOffice = "Delhi",
                            State = "DL"
                        },
                        new
                        {
                            ClientID = new Guid("c2010001-0000-0000-0000-000000000007"),
                            ClientDetails = "Startup incubator",
                            ClientEmployeeSizeRange = "20-100",
                            ClientName = "Sunrise Ventures",
                            ClientSource = "A1",
                            Country = "USA",
                            ServicingOffice = "San Francisco",
                            State = "CA"
                        },
                        new
                        {
                            ClientID = new Guid("c2010001-0000-0000-0000-000000000008"),
                            ClientDetails = "FinTech innovator",
                            ClientEmployeeSizeRange = "150-500",
                            ClientName = "GlobalEdge Ltd",
                            ClientSource = "A1",
                            Country = "Singapore",
                            ServicingOffice = "Singapore",
                            State = "SG"
                        },
                        new
                        {
                            ClientID = new Guid("c2010001-0000-0000-0000-000000000009"),
                            ClientDetails = "AI solutions",
                            ClientEmployeeSizeRange = "500-1000",
                            ClientName = "DataNest Inc",
                            ClientSource = "A2",
                            Country = "USA",
                            ServicingOffice = "Austin",
                            State = "TX"
                        },
                        new
                        {
                            ClientID = new Guid("c2010001-0000-0000-0000-000000000010"),
                            ClientDetails = "Healthcare analytics",
                            ClientEmployeeSizeRange = "200-600",
                            ClientName = "Peak Health",
                            ClientSource = "A1",
                            Country = "India",
                            ServicingOffice = "Hyderabad",
                            State = "AP"
                        },
                        new
                        {
                            ClientID = new Guid("c2010001-0000-0000-0000-000000000011"),
                            ClientDetails = "Digital marketing agency",
                            ClientEmployeeSizeRange = "100-400",
                            ClientName = "SkyLine Media",
                            ClientSource = "A2",
                            Country = "USA",
                            ServicingOffice = "Miami",
                            State = "FL"
                        },
                        new
                        {
                            ClientID = new Guid("c2010001-0000-0000-0000-000000000012"),
                            ClientDetails = "Smart grid tech",
                            ClientEmployeeSizeRange = "250-800",
                            ClientName = "NeoGrid Systems",
                            ClientSource = "A1",
                            Country = "Australia",
                            ServicingOffice = "Sydney",
                            State = "NSW"
                        },
                        new
                        {
                            ClientID = new Guid("c2010001-0000-0000-0000-000000000013"),
                            ClientDetails = "Green construction",
                            ClientEmployeeSizeRange = "100-300",
                            ClientName = "EarthWorks Ltd",
                            ClientSource = "A2",
                            Country = "India",
                            ServicingOffice = "Kochi",
                            State = "KL"
                        },
                        new
                        {
                            ClientID = new Guid("c2010001-0000-0000-0000-000000000014"),
                            ClientDetails = "Investment services",
                            ClientEmployeeSizeRange = "300-700",
                            ClientName = "BridgePoint Finance",
                            ClientSource = "A1",
                            Country = "USA",
                            ServicingOffice = "Chicago",
                            State = "IL"
                        },
                        new
                        {
                            ClientID = new Guid("c2010001-0000-0000-0000-000000000015"),
                            ClientDetails = "Medical device firm",
                            ClientEmployeeSizeRange = "150-450",
                            ClientName = "NovaCare Plus",
                            ClientSource = "A2",
                            Country = "USA",
                            ServicingOffice = "Seattle",
                            State = "WA"
                        },
                        new
                        {
                            ClientID = new Guid("c2010001-0000-0000-0000-000000000016"),
                            ClientDetails = "Artificial intelligence lab",
                            ClientEmployeeSizeRange = "80-200",
                            ClientName = "MindForge AI",
                            ClientSource = "A1",
                            Country = "USA",
                            ServicingOffice = "Palo Alto",
                            State = "CA"
                        },
                        new
                        {
                            ClientID = new Guid("c2010001-0000-0000-0000-000000000017"),
                            ClientDetails = "Autonomous vehicles R&D",
                            ClientEmployeeSizeRange = "300-900",
                            ClientName = "AutoPilot Ltd",
                            ClientSource = "A2",
                            Country = "India",
                            ServicingOffice = "Coimbatore",
                            State = "TN"
                        },
                        new
                        {
                            ClientID = new Guid("c2010001-0000-0000-0000-000000000018"),
                            ClientDetails = "Sustainable fabric maker",
                            ClientEmployeeSizeRange = "400-1200",
                            ClientName = "Riverstone Textiles",
                            ClientSource = "A1",
                            Country = "USA",
                            ServicingOffice = "Atlanta",
                            State = "GA"
                        },
                        new
                        {
                            ClientID = new Guid("c2010001-0000-0000-0000-000000000019"),
                            ClientDetails = "Renewable energy startup",
                            ClientEmployeeSizeRange = "200-600",
                            ClientName = "Ignite Energy",
                            ClientSource = "A2",
                            Country = "USA",
                            ServicingOffice = "Houston",
                            State = "TX"
                        },
                        new
                        {
                            ClientID = new Guid("c2010001-0000-0000-0000-000000000020"),
                            ClientDetails = "Construction AI tools",
                            ClientEmployeeSizeRange = "100-300",
                            ClientName = "QuantumBuild",
                            ClientSource = "A1",
                            Country = "Canada",
                            ServicingOffice = "Vancouver",
                            State = "BC"
                        },
                        new
                        {
                            ClientID = new Guid("c2010001-0000-0000-0000-000000000021"),
                            ClientDetails = "Online grocery service",
                            ClientEmployeeSizeRange = "50-250",
                            ClientName = "FoodVerse Co",
                            ClientSource = "A2",
                            Country = "India",
                            ServicingOffice = "Lucknow",
                            State = "UP"
                        },
                        new
                        {
                            ClientID = new Guid("c2010001-0000-0000-0000-000000000022"),
                            ClientDetails = "Industrial robotics",
                            ClientEmployeeSizeRange = "300-1000",
                            ClientName = "Wavelength Robotics",
                            ClientSource = "A1",
                            Country = "USA",
                            ServicingOffice = "Boston",
                            State = "MA"
                        },
                        new
                        {
                            ClientID = new Guid("c2010001-0000-0000-0000-000000000023"),
                            ClientDetails = "Marine ecology tech",
                            ClientEmployeeSizeRange = "100-600",
                            ClientName = "EcoHarbor",
                            ClientSource = "A2",
                            Country = "USA",
                            ServicingOffice = "Portland",
                            State = "OR"
                        },
                        new
                        {
                            ClientID = new Guid("c2010001-0000-0000-0000-000000000024"),
                            ClientDetails = "EdTech solutions",
                            ClientEmployeeSizeRange = "120-400",
                            ClientName = "BrightHive",
                            ClientSource = "A1",
                            Country = "India",
                            ServicingOffice = "Madurai",
                            State = "TN"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
